import { z } from 'zod';

export const surveySchema = z.object({
  q1_name: z.string().optional().nullable(),
  q1_location: z.string().optional().nullable(),
  q1_country: z.string().optional().nullable(),
  q1_phone: z.string().optional().nullable(),
  q1_experience: z.coerce.number({invalid_type_error: "Debe ser un número."}).optional().nullable(),
  q1_role: z.string().optional().nullable(),
  q2_services: z.string().optional().nullable(),
  q2_unique: z.string().optional().nullable(),
  q3_persona: z.string().optional().nullable(),
  q4_perception: z.array(z.string()).max(3, "Puedes seleccionar hasta 3 opciones.").optional().nullable(),
  q4_other: z.string().optional().nullable(),
  q5_emotions: z.array(z.string()).max(3, "Puedes seleccionar hasta 3 opciones.").optional().nullable(),
  q5_other: z.string().optional().nullable(),
  q6_why: z.string().optional().nullable(),
  q7_differentiation: z.array(z.string()).max(3, "Puedes seleccionar hasta 3 opciones.").optional().nullable(),
  q7_why: z.string().optional().nullable(),
  q7_other: z.string().optional().nullable(),
  q8_value: z.array(z.string()).max(3, "Puedes seleccionar hasta 3 opciones.").optional().nullable(),
  q8_other: z.string().optional().nullable(),
  q9_presence: z.array(z.string()).optional().nullable(),
  q9_other: z.string().optional().nullable(),
  q10_rating: z.number().min(1).max(10).optional().nullable(),
  q10_challenges: z.array(z.string()).max(3, "Puedes seleccionar hasta 3 desafíos.").optional().nullable(),
  q10_other: z.string().optional().nullable(),
  q11_training: z.string().optional().nullable(),
  q12_details: z.string().optional().nullable(),
  q13_colors: z.string().optional().nullable(),
  q14_hobby: z.string().optional().nullable(),
  q15_final: z.string().optional().nullable(),
  competitors: z.array(z.object({ name: z.string().optional() })).optional().nullable(),
});
